/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home3: typeof import('./src/components/Home3.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NavLeft: typeof import('./src/components/NavLeft.vue')['default']
    NavTop: typeof import('./src/components/NavTop.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
