services:
  - type: web
    name: compare.vue
    plan: free
    branch: main
    region: ohio
    repo: https://github.com/riodw/compare.vue
    env: static
    buildCommand: pnpm install && pnpm run build-only
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 24.13.1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
